services:
  - type: web
    name: nexstock
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: NexStock
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: nexstock
          property: hostURL
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false       # isi manual di dashboard Render
      - key: DB_PORT
        sync: false       # isi manual di dashboard Render
      - key: DB_DATABASE
        sync: false       # isi manual di dashboard Render
      - key: DB_USERNAME
        sync: false       # isi manual di dashboard Render
      - key: DB_PASSWORD
        sync: false       # isi manual di dashboard Render
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
